name: 'Get NeoForm Version'
description: 'Finds the latest NeoForm version matching a version search string'
author: Twelve Iterations

branding:
  icon: heart
  color: red

inputs:
  version:
    description: 'Version to search for (e.g., 1.21.11-* for wildcard matching)'
    required: true

outputs:
  version:
    description: 'The latest NeoForm version matching the search criteria'

runs:
  using: node20
  main: dist/index.js
